spring:
  datasource:
    url: jdbc:mysql://localhost:3306/linuxterminal?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 配置静态资源文件路径
  resources:
    static-locations: ["/templates/","/resources/","/static/","/public/"]

mybatis-plus:
  config-location: classpath:mybatis-config.xml
  #configuration:map-underscore-to-camel-case: true
  #可有可无 的mapper地址
  #mapper-locations: classpath:hmh/terminal/linux/dao/mapper/*/*.xml
  #映射类所在的包
  #type-aliases-package: com.study.project4.com.entity

#token配置
jwt:
  secret: coding-heminghao
  expiration: 3600000L * 24*7
  header: Authorization

#文件上传地址
filepath: D:\JavaEE_Porject\LinuxTerminalDemo\key\



